//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWLoginServiceApplication.RESTServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="results", Namespace="http://schemas.datacontract.org/2004/07/RESTWebService")]
    [System.SerializableAttribute()]
    public partial class results : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int loginIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int loginID {
            get {
                return this.loginIDField;
            }
            set {
                if ((this.loginIDField.Equals(value) != true)) {
                    this.loginIDField = value;
                    this.RaisePropertyChanged("loginID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RESTServiceReference.IRESTService")]
    public interface IRESTService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESTService/GetIDPassword", ReplyAction="http://tempuri.org/IRESTService/GetIDPasswordResponse")]
        PWLoginServiceApplication.RESTServiceReference.results GetIDPassword(string firstName, string lastName, int age);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESTService/GetIDPassword", ReplyAction="http://tempuri.org/IRESTService/GetIDPasswordResponse")]
        System.Threading.Tasks.Task<PWLoginServiceApplication.RESTServiceReference.results> GetIDPasswordAsync(string firstName, string lastName, int age);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRESTServiceChannel : PWLoginServiceApplication.RESTServiceReference.IRESTService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RESTServiceClient : System.ServiceModel.ClientBase<PWLoginServiceApplication.RESTServiceReference.IRESTService>, PWLoginServiceApplication.RESTServiceReference.IRESTService {
        
        public RESTServiceClient() {
        }
        
        public RESTServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RESTServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RESTServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RESTServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PWLoginServiceApplication.RESTServiceReference.results GetIDPassword(string firstName, string lastName, int age) {
            return base.Channel.GetIDPassword(firstName, lastName, age);
        }
        
        public System.Threading.Tasks.Task<PWLoginServiceApplication.RESTServiceReference.results> GetIDPasswordAsync(string firstName, string lastName, int age) {
            return base.Channel.GetIDPasswordAsync(firstName, lastName, age);
        }
    }
}
